SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
arch: sparc
copyrights:
- Copyright (C) 2020, 2025 embedded brains GmbH & Co. KG
component-type: generic
enabled-by: true
enabled-set: []
enabled-set-actions: []
enabled-set-feedback-mapping: {}
ident: sparc/${.:/component/name}/${.:/component/package-version}
links:
- role: use-package-component-template
  uid: /pkg/template/arch/component
- hash: null
  name: component
  role: input
  uid: ../component
pkg-type: workspace
type: pkg
workspace-type: component
